### ISSUE TITLE
Have just one facet model

### ISSUE THREAD

**Issue by gregtucker** [gregtucker/grain_hills#4]
We currently have two mountain-front facet models: one in a separate repo that I created, and one here in this repo, GrainFacet, which was created by @siccarpoint. We should merge these into just one model.

**Comment by SiccarPoint** [comment]
The one I created here was motivated by keeping up with the best practice you were introducing within GrainHills; in particular, the interfacing with the other modules living within GrainHills (e.g., irradiator) and the nice packaging you have produced.

I have no preference which survives. They both look very similar. There must be some differences though, as MountainFrontModel never suffered the top hit bug.

**Comment by gregtucker** [comment]
Along these lines, merge grain_facet.py and grain_facet_model.py
